"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[palette]
os = "#ACB0BE" 
closer = "p:os"
muave = "#C6A0F6"
lavender = "#B7BDF8"
blue = "#8AADF4"
green = "#A6DA95"
red = "#ED8796"
peach = "#F5A97F"
yellow = "#EED49F"
maroon = "#EE99A0"
teal = "#8BD5CA"
sapphire = "#7DC4E4"

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  style = "plain"
  template = "asdasd"
  foreground = "p:os"
  type = "root"
  
  [[blocks.segments]]
  style = "plain"
  template = "{{.Icon}} "
  foreground = "p:os"
  type = "os"

  [[blocks.segments]]
  style = "plain"
  foreground = "p:muave"
  template = "{{ .UserName }}@{{ .HostName }} "
  type = "session"

  [[blocks.segments]]
  style = "plain"
  type = "path"
  template = " {{ .Path }} "
  foreground = "p:blue"

    [blocks.segments.properties]
    folder_icon = ""
    home_icon = "~"
    style = "agnoster_short"
  
  [[blocks.segments]]
  foreground_templates = [ "{{ if gt .Code 0 }}p:red{{ end }}" ]
  foreground = "p:green"
  style = "plain"
  template = " "
  type = "status"

    [blocks.segments.properties]
    always_enabled = false

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  style = "plain"
  foreground = "p:lavender"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:peach{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:maroon{{ end }}",
  "{{ if gt .Ahead 0 }}p:teal{{ end }}",
  "{{ if gt .Behind 0 }}p:sapphire{{ end }}"
]
  template = " {{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    branch_icon = "\ue725 "
    cherry_pick_icon = "\ue29b "
    commit_icon = "\uf417 "
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = false
    merge_icon = "\ue727 "
    no_commits_icon = "\uf0c3 "
    rebase_icon = "\ue728 "
    revert_icon = "\uf0e2 "
    tag_icon = "\uf412 "

  [[blocks.segments]]
  type = "time"
  foreground = "p:green"
  template = "\ue641 {{ .CurrentDate | date .Format }} "
  style = "plain"

    [blocks.segments.properties]
    time_format = "15:04:05"


[[blocks]]
type = "prompt"
newline = true
alignment = "left"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  template = "\u276f"
  foreground = "green"

